# Generated by Django 5.0 on 2024-01-04 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_book_waiting_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='waiting_list',
        ),
    ]
